server:
  port: 8080

spring:
  application:
    name: gateway-service

gateway:
  server:
    webFlux:
      routes:
        - id: user-service-route
          uri: http://localhost:8081/
          predicates:
            - Path=/users/**
        - id: inscription-service-route
          uri: http://localhost:8082/
          predicates:
            - Path=/inscriptions/**
