server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               
      routes:
        - id: user-service
          uri: lb://USER-SERVICE      
          predicates:
            - Path=/users/**
        - id: inscription-service
          uri: lb://INSCRIPTION-SERVICE
          predicates:
            - Path=/inscriptions/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
