
server:
  port: 8080   

spring:
  application:
    name: gateway-service

  config:
    import: "optional:configserver:http://localhost:8888"
  
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:4200"
              - "http://127.0.0.1:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      
      routes:
        # Routes via Eureka avec load balancing
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0
        
        - id: inscription-service
          uri: lb://inscription-service
          predicates:
            - Path=/inscriptions/**
          filters:
            - StripPrefix=0
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
